"""
Эталонный справочник услуг MedServicePrice.kz (55+ позиций).
Используется seed.py и документирует синонимы для нормализатора.
"""
import json

CATEGORIES = [
    {"name": "Лабораторные анализы", "slug": "analizy", "icon_name": "flask-conical", "sort_order": 1},
    {"name": "МРТ", "slug": "mrt", "icon_name": "scan", "sort_order": 2},
    {"name": "УЗИ", "slug": "uzi", "icon_name": "activity", "sort_order": 3},
    {"name": "Диагностика", "slug": "diagnostika", "icon_name": "heart-pulse", "sort_order": 4},
    {"name": "Приём врача", "slug": "priyom-vracha", "icon_name": "stethoscope", "sort_order": 5},
    {"name": "Стоматология", "slug": "stomatologiya", "icon_name": "smile", "sort_order": 6},
    {"name": "Услуги из прайсов", "slug": "pricelist", "icon_name": "file-text", "sort_order": 7},
]


def _aliases(*items: str) -> str:
    return json.dumps(list(items), ensure_ascii=False)


SERVICES = [
    # ── Лабораторные анализы ──────────────────────────────────────────────────
    {"category_slug": "analizy", "name": "Общий анализ крови (ОАК)",
     "aliases": _aliases(
         "ОАК", "Клинический анализ крови", "CBC", "Общий анализ", "Анализ крови общий", "Кровь общий",
         "Complete Blood Count", "Общий анализ крови (без лейкоцитарной формулы",
         "Анализ крови. Общий анализ крови",
         "Клинический анализ крови с лейкоцитарной формулой",
     )},
    {"category_slug": "analizy", "name": "Общий анализ мочи (ОАМ)",
     "aliases": _aliases("ОАМ", "Анализ мочи", "Урина общий", "UAM", "Моча общий")},
    {"category_slug": "analizy", "name": "Биохимический анализ крови (расширенный)",
     "aliases": _aliases("Биохимия крови", "Биохимия расширенная", "БАК", "Biochemistry", "Биохимия")},
    {"category_slug": "analizy", "name": "Глюкоза крови",
     "aliases": _aliases("Глюкоза", "Сахар крови", "Glucose", "Глюкоза натощак", "Глюкоза (в крови)")},
    {"category_slug": "analizy", "name": "Холестерин общий",
     "aliases": _aliases("Холестерин", "Cholesterol", "Общий холестерин")},
    {"category_slug": "analizy", "name": "АЛТ (аланинаминотрансфераза)",
     "aliases": _aliases("АЛТ", "ALT", "Аланинаминотрансфераза")},
    {"category_slug": "analizy", "name": "АСТ (аспартатаминотрансфераза)",
     "aliases": _aliases("АСТ", "AST", "Аспартатаминотрансфераза")},
    {"category_slug": "analizy", "name": "Билирубин общий",
     "aliases": _aliases("Билирубин", "Bilirubin", "Билирубин total")},
    {"category_slug": "analizy", "name": "Креатинин",
     "aliases": _aliases("Creatinine", "Креатинин крови")},
    {"category_slug": "analizy", "name": "Мочевина",
     "aliases": _aliases("Urea", "Мочевина крови")},
    {"category_slug": "analizy", "name": "СОЭ",
     "aliases": _aliases(
         "Скорость оседания эритроцитов", "ESR", "СОЭ крови",
         "СОЭ (Cкорость Оседания Эритроцитов", "Скорость оседания эритроцитов (СОЭ)",
     )},
    {"category_slug": "analizy", "name": "ТТГ (тиреотропный гормон)",
     "aliases": _aliases("ТТГ", "TSH", "Гормон щитовидной железы", "Тиреотропин")},
    {"category_slug": "analizy", "name": "Т3 свободный",
     "aliases": _aliases("FT3", "Т3", "Трийодтиронин свободный")},
    {"category_slug": "analizy", "name": "Т4 свободный",
     "aliases": _aliases("FT4", "Т4", "Тироксин свободный")},
    {"category_slug": "analizy", "name": "АТ-ТПО",
     "aliases": _aliases("Антитела к ТПО", "Anti-TPO", "ТПО")},
    {"category_slug": "analizy", "name": "Коагулограмма (МНО, ПВ, АЧТВ)",
     "aliases": _aliases("Коагулограмма", "Свертываемость крови", "МНО", "Гемостаз", "АЧТВ")},
    {"category_slug": "analizy", "name": "Ферритин",
     "aliases": _aliases("Ferritin", "Ферритин крови")},
    {"category_slug": "analizy", "name": "Витамин D (25-OH)",
     "aliases": _aliases("Витамин D", "Vitamin D", "25-OH витамин D", "Кальциферол")},
    {"category_slug": "analizy", "name": "Витамин B12",
     "aliases": _aliases("B12", "Кобаламин", "Цианокобаламин")},
    {"category_slug": "analizy", "name": "ПСА общий",
     "aliases": _aliases("ПСА", "PSA", "Простатический специфический антиген")},
    {"category_slug": "analizy", "name": "Гликированный гемоглобин (HbA1c)",
     "aliases": _aliases("HbA1c", "Гликированный гемоглобин", "Гликозилированный гемоглобин")},
    {"category_slug": "analizy", "name": "Анализ на ВИЧ",
     "aliases": _aliases("ВИЧ", "HIV", "Anti-HIV", "ИФА ВИЧ")},
    {"category_slug": "analizy", "name": "Гепатит B (HBsAg)",
     "aliases": _aliases("HBsAg", "Гепатит B", "Hepatitis B", "Антиген HBs")},
    {"category_slug": "analizy", "name": "Сифилис (RW)",
     "aliases": _aliases("RW", "RPR", "Сифилис", "Реакция Вассермана")},
    {"category_slug": "analizy", "name": "IgE общий",
     "aliases": _aliases("IgE", "Иммуноглобулин E", "Общий IgE")},
    {"category_slug": "analizy", "name": "Мазок на флору",
     "aliases": _aliases("Мазок", "Мазок на микрофлору", "Бактериоскопия мазка")},
    {"category_slug": "analizy", "name": "Кальций общий",
     "aliases": _aliases("Кальций", "Calcium", "Ca общий")},
    {"category_slug": "analizy", "name": "Тестостерон общий",
     "aliases": _aliases("Тестостерон", "Testosterone")},
    {"category_slug": "analizy", "name": "Эстрадиол",
     "aliases": _aliases("Estradiol", "E2")},
    {"category_slug": "analizy", "name": "Пролактин",
     "aliases": _aliases("Prolactin", "ПРЛ")},
    {"category_slug": "analizy", "name": "Кортизол",
     "aliases": _aliases("Cortisol", "Кортизол крови")},
    {"category_slug": "analizy", "name": "Железо сывороточное",
     "aliases": _aliases("Железо", "Сывороточное железо", "Iron", "Fe")},
    {"category_slug": "analizy", "name": "ПЦР на COVID-19",
     "aliases": _aliases("ПЦР-тест на COVID-19", "COVID-19 ПЦР", "ПЦР диагностика COVID-19", "Коронавирус ПЦР")},
    # ── МРТ ───────────────────────────────────────────────────────────────────
    {"category_slug": "mrt", "name": "МРТ головного мозга",
     "aliases": _aliases("МРТ мозга", "МРТ головы", "MRI brain", "МРТ ГМ", "МРТ головного мозга без контраста")},
    {"category_slug": "mrt", "name": "МРТ позвоночника (поясничный отдел)",
     "aliases": _aliases("МРТ поясницы", "МРТ LS позвонков", "МРТ поясничный", "МРТ L-S", "МРТ пояснично-крестцового отдела")},
    {"category_slug": "mrt", "name": "МРТ позвоночника (шейный отдел)",
     "aliases": _aliases("МРТ шеи", "МРТ шейного отдела", "МРТ CS", "МРТ шейного отдела позвоночника")},
    {"category_slug": "mrt", "name": "МРТ коленного сустава",
     "aliases": _aliases("МРТ колена", "МРТ коленного", "MRI knee", "МРТ коленного сустава")},
    {"category_slug": "mrt", "name": "МРТ плечевого сустава",
     "aliases": _aliases("МРТ плеча", "МРТ плечевого", "MRI shoulder")},
    {"category_slug": "mrt", "name": "МРТ тазобедренных суставов",
     "aliases": _aliases("МРТ таза", "МРТ тазобедренного сустава", "МРТ ТБС")},
    # ── УЗИ ───────────────────────────────────────────────────────────────────
    {"category_slug": "uzi", "name": "УЗИ органов брюшной полости",
     "aliases": _aliases("УЗИ брюшной полости", "УЗИ ОБП", "УЗИ живота", "Abdominal ultrasound", "УЗИ печени и желчного")},
    {"category_slug": "uzi", "name": "УЗИ щитовидной железы",
     "aliases": _aliases("УЗИ щитовидки", "УЗИ ЩЖ", "Thyroid ultrasound")},
    {"category_slug": "uzi", "name": "УЗИ почек",
     "aliases": _aliases("УЗИ почек и мочевого", "УЗИ мочевыделительной системы", "Kidney ultrasound")},
    {"category_slug": "uzi", "name": "УЗИ сердца (ЭхоКГ)",
     "aliases": _aliases("ЭхоКГ", "Эхокардиография", "УЗИ сердца", "EchoCG")},
    {"category_slug": "uzi", "name": "УЗИ молочных желёз",
     "aliases": _aliases("УЗИ молочных желез", "УЗИ груди", "Mammary ultrasound")},
    {"category_slug": "uzi", "name": "УЗИ малого таза",
     "aliases": _aliases("УЗИ органов малого таза", "УЗИ МТ", "Transvaginal ultrasound", "УЗИ ОМТ")},
    {"category_slug": "uzi", "name": "УЗИ сосудов шеи (БЦА)",
     "aliases": _aliases("УЗДГ БЦА", "УЗИ БЦА", "Дуплексное сканирование БЦА", "УЗИ сосудов шеи")},
    {"category_slug": "uzi", "name": "УЗИ предстательной железы",
     "aliases": _aliases("УЗИ простаты", "УЗИ ПЖ", "Prostate ultrasound")},
    # ── Диагностика ───────────────────────────────────────────────────────────
    {"category_slug": "diagnostika", "name": "КТ головного мозга",
     "aliases": _aliases("КТ головы", "КТ ГМ", "CT brain", "Компьютерная томография головы")},
    {"category_slug": "diagnostika", "name": "КТ органов грудной клетки",
     "aliases": _aliases("КТ лёгких", "КТ грудной клетки", "CT chest")},
    {"category_slug": "diagnostika", "name": "Рентген грудной клетки",
     "aliases": _aliases("Рентген ОГК", "Рентгенография грудной клетки", "Флюорография", "ФЛГ")},
    {"category_slug": "diagnostika", "name": "ЭКГ (электрокардиография)",
     "aliases": _aliases("ЭКГ", "ECG", "Электрокардиограмма")},
    {"category_slug": "diagnostika", "name": "ЭЭГ (электроэнцефалография)",
     "aliases": _aliases("ЭЭГ", "EEG")},
    {"category_slug": "diagnostika", "name": "ФГДС (гастроскопия)",
     "aliases": _aliases("ФГДС", "Гастроскопия", "ЭГДС", "EGDS")},
    {"category_slug": "diagnostika", "name": "Колоноскопия",
     "aliases": _aliases("ФКС", "Colonoscopy", "Инструментальное исследование толстой кишки")},
    {"category_slug": "diagnostika", "name": "Холтер ЭКГ (суточное мониторирование)",
     "aliases": _aliases("Холтер", "СМЭКГ", "Суточное мониторирование ЭКГ", "Holter")},
    {"category_slug": "diagnostika", "name": "Суточное мониторирование АД",
     "aliases": _aliases("СМАД", "Холтер АД", "Мониторирование давления")},
    # ── Приём врача ───────────────────────────────────────────────────────────
    {"category_slug": "priyom-vracha", "name": "Приём терапевта (первичный)",
     "aliases": _aliases("Терапевт первичный", "Консультация терапевта", "Приём врача терапевта", "Терапевт")},
    {"category_slug": "priyom-vracha", "name": "Приём кардиолога",
     "aliases": _aliases("Кардиолог консультация", "Консультация кардиолога", "Cardiologist", "Кардиолог")},
    {"category_slug": "priyom-vracha", "name": "Приём невролога",
     "aliases": _aliases("Невролог консультация", "Консультация невролога", "Невропатолог", "Невролог")},
    {"category_slug": "priyom-vracha", "name": "Приём гинеколога",
     "aliases": _aliases("Гинеколог", "Консультация гинеколога", "Gynecologist")},
    {"category_slug": "priyom-vracha", "name": "Приём уролога",
     "aliases": _aliases("Уролог", "Консультация уролога", "Urologist")},
    {"category_slug": "priyom-vracha", "name": "Приём эндокринолога",
     "aliases": _aliases("Эндокринолог", "Консультация эндокринолога")},
    {"category_slug": "priyom-vracha", "name": "Приём ЛОР-врача",
     "aliases": _aliases("ЛОР", "Отоларинголог", "Консультация ЛОР", "Оториноларинголог")},
    {"category_slug": "priyom-vracha", "name": "Приём дерматолога",
     "aliases": _aliases("Дерматолог", "Консультация дерматолога", "Дерматовенеролог")},
    {"category_slug": "priyom-vracha", "name": "Приём офтальмолога",
     "aliases": _aliases("Офтальмолог", "Окулист", "Консультация офтальмолога")},
    {"category_slug": "priyom-vracha", "name": "Приём педиатра",
     "aliases": _aliases("Педиатр", "Консультация педиатра", "Детский врач")},
    {"category_slug": "priyom-vracha", "name": "Приём гастроэнтеролога",
     "aliases": _aliases("Гастроэнтеролог", "Консультация гастроэнтеролога", "Прием врача-гастроэнтеролога")},
    # ── Стоматология ──────────────────────────────────────────────────────────
    {"category_slug": "stomatologiya", "name": "Лечение кариеса (1 поверхность)",
     "aliases": _aliases("Кариес лечение", "Пломба 1 поверхность", "Лечение зуба", "Пломбирование")},
    {"category_slug": "stomatologiya", "name": "Профессиональная чистка зубов (Air Flow)",
     "aliases": _aliases("Чистка зубов", "Air Flow", "Airflow", "Профчистка", "Гигиена полости рта", "Снятие зубного камня")},
    {"category_slug": "stomatologiya", "name": "Удаление зуба (простое)",
     "aliases": _aliases("Удаление зуба", "Экстракция зуба", "Удаление постоянного зуба")},
    {"category_slug": "stomatologiya", "name": "Лечение пульпита",
     "aliases": _aliases("Пульпит", "Лечение корневых каналов", "Эндодонтическое лечение")},
    {"category_slug": "stomatologiya", "name": "Отбеливание зубов",
     "aliases": _aliases("Отбеливание", "Bleaching", "Профессиональное отбеливание")},
]
